from django.contrib import admin
from yedo.models import *
# Register your models here.

admin.site.register(Student)
admin.site.register(JobType)
admin.site.register(DisponilityType)
admin.site.register(Zip)
admin.site.register(Stats)
admin.site.register(Achat)
admin.site.register(Employeur)
admin.site.register(Demande)
admin.site.register(JourDispo)
admin.site.register(Premium)
admin.site.register(AdminUser)
admin.site.register(Referral)
admin.site.register(StreetMarketer)
admin.site.register(StreetMarketerReferral)
admin.site.register(LanguageText)
admin.site.register(LanguageLevel)
admin.site.register(LanguageStudent)
admin.site.register(Experience)
admin.site.register(Adresse)
admin.site.register(ConfigDemande)
admin.site.register(NewsLetter)
admin.site.register(StudyType)
admin.site.register(StudyDomain)
admin.site.register(StudyLevel)
admin.site.register(PhoneValidate)
admin.site.register(Periode)
admin.site.register(CodePromo)