"""
Django settings for yedo project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PRICE_UNLOCK = 3
GOOGLE_KEY = "googlekey"
SPREADSHEET_ID = "spreadsheetkey"
MJ_APIKEY_PUBLIC = 'mailjetpublickey'
MJ_APIKEY_SECRET = 'mailjetsecretket'
SMSAPISECRETKEY = 'smsapikey'

DOMAIN = "https://yedo.io"

#S_T_R_I_P_E_KEY = 'sk_test_NMFE0yspPAPBmMswkZjCnZQi00JvSMGT5H'
S_T_R_I_P_E_KEY = 'stripekey'
S_T_R_I_P_E_ENDPOINT = 'stripewebhook'
#S_T_R_I_P_E_ENDPOINT = 'whsec_yBwzZLYpJPFoPwQdZt9wKKNnCfcZ9n3H'

mailjettemplates = {
    'pass_reset': 1008085,
    'new_account_student': 1020425,
    'new_account_employeur':1020431,
    'notif_student': 1020423,
    'notif_employeur': 1020440,
    'achat_credits': 1023692,
    'achat_premium': 1023965,
    'students_reminder': 1029119
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yyvg6@4#p7#14yaht-kei4l5@k*-=t^8boq8%3#0r%^5j$h2ck'
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_COOKIE_AGE = 8035200
CSRF_USE_SESSIONS = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'yedo',
    'students',
    'entreprises',
    'handleauth',
    'storages',
    'sorl.thumbnail'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'redirect_to_non_www.middleware.RedirectToNonWww',
]

ROOT_URLCONF = 'yedo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yedo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'yedodb',
    #     'USER': 'yedo_admin',
    #     'PASSWORD': 'BeJ0bs1357',
    #     'HOST': 'localhost',
    #     'PORT': '',
    # }
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'USER': 'doadmin',
    #     'PASSWORD': 'pb248onmsuttsb4b',
    #     'HOST': 'db-postgresql-ams3-49962-do-user-6540861-0.db.ondigitalocean.com',
    #     'PORT': '25060',
    #     'NAME': 'yedo',
    #     'OPTIONS': {'sslmode': 'require'}
    # }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

DBBACKUP_STORAGE = 'yedo.storage_backends.DBStorage'
DBBACKUP_STORAGE_OPTIONS = {
    'access_key': 'access',
    'secret_key': 'secret',
    'bucket_name': 'yedo'
}

STATICFILES_STORAGE = 'yedo.storage_backends.StaticStorage'
DEFAULT_FILE_STORAGE = 'yedo.storage_backends.MediaStorage'
AWS_ACCESS_KEY_ID = "accesskeyid"
AWS_SECRET_ACCESS_KEY = "secret"
AWS_STORAGE_BUCKET_NAME = "yedo"
AWS_S3_CUSTOM_DOMAIN = 's3.eu-west-3.amazonaws.com/%s' % AWS_STORAGE_BUCKET_NAME


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'yedo/static'),
]
STATIC_URL = 'https://%s/static/' % (AWS_S3_CUSTOM_DOMAIN)

MEDIA_URL = 'https://%s/media/' % (AWS_S3_CUSTOM_DOMAIN)



