# Generated by Django 2.2 on 2019-09-12 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('is_visible', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('zip', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('validated', models.BooleanField(default=False)),
                ('default_password', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('french', models.IntegerField(default=0)),
                ('english', models.IntegerField(default=0)),
                ('dutch', models.IntegerField(default=0)),
                ('signup_step', models.IntegerField(default=1)),
                ('jobs_wanted', models.ManyToManyField(to='yedo.JobType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
