# Generated by Django 2.2 on 2019-09-16 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0004_disponilites_disponilitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dispo_explications',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dispo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.DisponilityType'),
        ),
        migrations.AddField(
            model_name='student',
            name='jours_dispo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='soiree',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stage_remunere',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Disponilites',
        ),
    ]
