# Generated by Django 2.2 on 2019-09-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0007_auto_20190916_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='default_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeur',
            name='language',
            field=models.CharField(blank=True, default='fr_FR', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeur',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
