# Generated by Django 2.2 on 2019-09-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0009_employeur_signup_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dispos_set',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
