# Generated by Django 2.2 on 2019-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0011_auto_20190916_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='favoris',
            field=models.ManyToManyField(to='yedo.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='exp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='salary',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
