# Generated by Django 2.2 on 2019-09-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0012_auto_20190917_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('student_accepted', models.BooleanField(blank=True, default=False, null=True)),
                ('comment', models.CharField(blank=True, max_length=10000, null=True)),
                ('salary_proposed', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('dispo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.DisponilityType')),
                ('employeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Employeur')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Student')),
            ],
        ),
    ]
