# Generated by Django 2.2 on 2019-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0013_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='weeks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
