# Generated by Django 2.2 on 2019-09-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0014_demande_weeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clics_from_fb', models.IntegerField(default=0)),
            ],
        ),
    ]
