# Generated by Django 2.2 on 2019-09-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0015_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='plan3_clics',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='clics_from_fb',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
