# Generated by Django 2.2 on 2019-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0016_auto_20190918_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='interest_in_plan3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
