# Generated by Django 2.2 on 2019-09-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0018_employeur_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('employeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Employeur')),
            ],
        ),
    ]
