# Generated by Django 2.2 on 2019-09-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0020_employeur_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
