# Generated by Django 2.2 on 2019-09-18 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0021_demande_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDemande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.IntegerField(blank=True, default=0, null=True)),
                ('salary', models.FloatField(blank=True, default=0, null=True)),
                ('comment', models.CharField(blank=True, max_length=10000, null=True)),
                ('employeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Employeur')),
            ],
        ),
    ]
