# Generated by Django 2.2 on 2019-09-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0022_configdemande'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='student_refused',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
