# Generated by Django 2.2 on 2019-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0023_demande_student_refused'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
