# Generated by Django 2.2 on 2019-09-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0025_auto_20190920_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
