# Generated by Django 2.2 on 2019-09-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0026_auto_20190920_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
