# Generated by Django 2.2 on 2019-09-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0027_auto_20190920_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='picture_url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
