# Generated by Django 2.2.5 on 2019-09-22 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0028_jobtype_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourDispo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employeur',
            old_name='premium',
            new_name='is_premium',
        ),
        migrations.AddField(
            model_name='employeur',
            name='payment_method',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='employeur',
            name='zip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Zip'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nb_jours_dispos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='student',
            name='jours_dispo',
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('employeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Employeur')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='jours_dispo',
            field=models.ManyToManyField(to='yedo.JourDispo'),
        ),
    ]
