# Generated by Django 2.2 on 2019-09-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0029_auto_20190922_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeur',
            name='favoris',
            field=models.ManyToManyField(blank=True, to='yedo.Student'),
        ),
    ]
