# Generated by Django 2.2 on 2019-09-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0030_auto_20190923_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeur',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
