# Generated by Django 2.2 on 2019-10-01 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0032_auto_20190930_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeur',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='jobs_wanted',
            field=models.ManyToManyField(blank=True, to='yedo.JobType'),
        ),
        migrations.AlterField(
            model_name='student',
            name='jours_dispo',
            field=models.ManyToManyField(blank=True, to='yedo.JourDispo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.ManyToManyField(blank=True, to='yedo.Rating'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
