# Generated by Django 2.2 on 2019-10-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0034_auto_20191002_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount_sent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_reminder_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='unsubscribed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
