# Generated by Django 2.2 on 2019-10-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0035_auto_20191004_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='permis',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
