# Generated by Django 2.2 on 2019-10-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0037_auto_20191006_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(blank=True, max_length=1000, null=True)),
                ('duree', models.IntegerField(blank=True, default=0, null=True)),
                ('contact', models.CharField(blank=True, max_length=1000, null=True)),
                ('employeur', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='yedo.Experience'),
        ),
    ]
