# Generated by Django 2.2 on 2019-10-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0039_auto_20191007_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_fr', models.CharField(blank=True, max_length=1000, null=True)),
                ('value_nl', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_fr', models.CharField(blank=True, max_length=1000, null=True)),
                ('value_nl', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_fr', models.CharField(blank=True, max_length=1000, null=True)),
                ('value_nl', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='diplome',
        ),
        migrations.RemoveField(
            model_name='student',
            name='domaine',
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(blank=True, default=False, null=True)),
                ('referred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred', to='yedo.Student')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer', to='yedo.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='study_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.StudyDomain'),
        ),
        migrations.AddField(
            model_name='student',
            name='study_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.StudyLevel'),
        ),
        migrations.AddField(
            model_name='student',
            name='study_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.StudyType'),
        ),
    ]
