# Generated by Django 2.2 on 2019-10-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0040_auto_20191007_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('value_nl', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('value_nl', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='employeur',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='logos_employeurs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='student_pictures'),
        ),
        migrations.CreateModel(
            name='LanguageStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.LanguageText')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.LanguageLevel')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='languages',
            field=models.ManyToManyField(blank=True, to='yedo.LanguageStudent'),
        ),
    ]
