# Generated by Django 2.2 on 2019-10-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0042_streetmarketer_streetmarketerreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_validated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='PhoneValidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('sent', models.BooleanField(blank=True, default=False, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Student')),
            ],
        ),
    ]
