# Generated by Django 2.2 on 2019-10-21 11:56

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0043_auto_20191017_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dutch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='english',
        ),
        migrations.RemoveField(
            model_name='student',
            name='french',
        ),
        migrations.AddField(
            model_name='student',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
