# Generated by Django 2.2 on 2019-10-27 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yedo', '0044_auto_20191021_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(blank=True, max_length=50, null=True)),
                ('is_visible', models.BooleanField(blank=True, default=True, null=True)),
                ('intern_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='configdemande',
            name='dispo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.DisponilityType'),
        ),
        migrations.AddField(
            model_name='configdemande',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.JobType'),
        ),
        migrations.AddField(
            model_name='demande',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.JobType'),
        ),
        migrations.AddField(
            model_name='demande',
            name='jours',
            field=models.ManyToManyField(to='yedo.JourDispo'),
        ),
        migrations.AddField(
            model_name='employeur',
            name='phone_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonevalidate',
            name='employeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Employeur'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_visible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(blank=True, max_length=1000, null=True)),
                ('numero', models.CharField(blank=True, max_length=1000, null=True)),
                ('nom', models.CharField(blank=True, max_length=1000, null=True)),
                ('zip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Zip')),
            ],
        ),
        migrations.AddField(
            model_name='configdemande',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Adresse'),
        ),
        migrations.AddField(
            model_name='configdemande',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Periode'),
        ),
        migrations.AddField(
            model_name='demande',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Adresse'),
        ),
        migrations.AddField(
            model_name='demande',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yedo.Periode'),
        ),
        migrations.AddField(
            model_name='employeur',
            name='adresses',
            field=models.ManyToManyField(blank=True, to='yedo.Adresse'),
        ),
    ]
